export const directory = {
  name: "root",
  toggled: true,
  children: [
    {
      id: 1,
      name: "Archivos Word",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 63,
      type: "adult",
      path: [0],
      extension: "folder",
      children: [
        {
          id: 2,
          name: "Pendientes",
          fecha_modificacion: "Baran",
          modificado_por: 1987,
          tamaño: 34,
          type: "adult",
          parentId: 1,
          path: [0, 0],
          extension: "txt",
        },
      ],
    },

    {
      id: 3,
      name: "Archivos Excel",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 63,
      type: "adult",
      path: [0],
      extension: "folder",
      children: [
        {
          id: 4,
          name: "Pendientes",
          fecha_modificacion: "Baran",
          modificado_por: 1987,
          tamaño: 34,
          type: "adult",
          parentId: 1,
          path: [0, 0],
          extension: "txt",
        },
      ],
    },
  ],
};

export const directoryTree = {
  name: "root",
  toggled: true,
  children: [
    {
      id: 1,
      name: "Container 1",
      tamaño: "12GB",
      Subcarpetas: "Subcontainer",
      extension: "folder",
      archivos: "5",
      carpetas: "2",
      ruta: "container1",
      fechaMod: "12 jul 2021",
      modifPor: "Admin",
      children: [
        {
          id: 1.1,
          name: "child1",
          tamaño: "12GB",
          Subcarpetas: "Subcontainer",
          extension: "folder",
          archivos: "5",
          carpetas: "2",
          ruta: "container1",
          fechaMod: "12 jul 2021",
          modifPor: "Admin",
          children: [
            {
              id: 1.12,
              name: "child1_2.docx",
              tamaño: "12GB",
              Subcarpetas: "Subcontainer",
              extension: "docx",
              ruta: "container1/child1",
              fechaMod: "12 jul 2021",
              modifPor: "Admin",
            },
          ],
        },
        {
          id: 1.2,
          name: "child2",
          tamaño: "12GB",
          Subcarpetas: "Subcontainer",
          extension: "docx",
          ruta: "container1/child1",
          fechaMod: "12 jul 2021",
          modifPor: "Admin",
        },
      ],
    },
    {
      id: 2,
      name: "Container 2",
      tamaño: "12GB",
      Subcarpetas: "Subcontainer",
      extension: "folder",
      archivos: "5",
      carpetas: "2",
      ruta: "container1",
      fechaMod: "12 jul 2021",
      modifPor: "Admin",
      children: [
        {
          id: 2.1,
          name: "child2.1",
          tamaño: "12GB",
          Subcarpetas: "Subcontainer",
          extension: "folder",
          archivos: "5",
          carpetas: "2",
          ruta: "container2",
          fechaMod: "12 jul 2021",
          modifPor: "Admin",
          children: [
            {
              id: 2.12,
              name: "child2.2.docx",
              tamaño: "12GB",
              Subcarpetas: "Subcontainer",
              extension: "docx",
              ruta: "container1/child1",
              fechaMod: "12 jul 2021",
              modifPor: "Admin",
            },
          ],
        },
        {
          id: 2.2,
          name: "child2.2",
          tamaño: "12GB",
          Subcarpetas: "Subcontainer",
          extension: "docx",
          ruta: "container1/child1",
          fechaMod: "12 jul 2021",
          modifPor: "Admin",
        },
      ],
    },
  ],
};
