export const types = {
  uiOpenModal: "[ui] Open modal",
  uiCloseModal: "[ui] Close modal",
  uiOpenModalPropiedades: "[ui] Open modal Propiedades",
  uiCloseModalPropiedades: "[ui] Close modal Propiedades",
  eventOpenModalWith: "[gestion] Open modal With",

  gestionSetActive: "[gestion] Set active",
  gestionLogout: "[gestion] Start clear logout",
  gestionClearActive: "[gestion] Clear active gestion",
  gestionSetActiveCopy: "[gestion] Set active copy",
  gestionSetActiveView: "[gestion] Set active item gridView",

  gestionSetActiveProps: "[gestion] Set active object propiedades",
  gestionSelectFavorito: "[gestion] add favorito",
  gestionDeleteFvorito: "[gestion] delete favorito",
  gestionAddHistory: "[gestion] add history item",
  gestionAddPosition: "[gestion] add item position",
  gestionDeletePosition: "[gestion] delete item position",

  gestionStartAddNew: "[gestion] Start add new",
  gestionAddNew: "[gestion] Add new",
  gestionUpdate: "[gestion] gestion updted",
  gestionDelated: "[gestion] gestion delated",
  gestionLoaded: "[gestion] gestions loaded",
  gestionLoadedView:"[gestion] gestions loaded",

  authChecking: "[auth] Checking login state",
  authCheckingFinish: "[auth] Finish checking login state",
  authStartLogin: "[auth] Start login",
  authFinishLogin: "[auth] Finish start login",
  authStartTokenRenew: "[auth] Start token renew",
  authLogout: "[auth] Start logout",
  authChangeUsuario2bc: "[auth] Change type usuario to 2bc",
  authDatosToken: "[auth] Set Data Vec and Exp Token",
  authsetDatos: "[auth] set data token",
};
